CREATE TABLE `QA_PLACES`
(
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `VERSION` int(11) DEFAULT NULL,

  PRIMARY KEY(`ID`)
)
DEFAULT CHARSET=utf8;

ALTER TABLE `QA_PLACES` add `VALID` bit(1) DEFAULT NULL;

ALTER TABLE `QA_PLACES` add `DITIB_CODE` varchar(20) DEFAULT NULL;
ALTER TABLE `QA_PLACES` add `CAGEDATA_KEY` varchar(20) DEFAULT NULL;
ALTER TABLE `QA_PLACES` add `OSM_ID` varchar(20) DEFAULT NULL;
