CREATE TABLE `STATISTICS`
(
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `VERSION` int(11) DEFAULT NULL,

  PRIMARY KEY(`ID`)
)
DEFAULT CHARSET=utf8;

ALTER TABLE `STATISTICS` add `VALID` bit(1) DEFAULT NULL;
