ALTER TABLE `STATISTICS` add `MIN_LAT` double DEFAULT NULL;
ALTER TABLE `STATISTICS` add `MIN_LON` double DEFAULT NULL;

ALTER TABLE `STATISTICS` add `MAX_LAT` double DEFAULT NULL;
ALTER TABLE `STATISTICS` add `MAX_LON` double DEFAULT NULL;

ALTER TABLE `STATISTICS` add `CENTROID_LAT` double DEFAULT NULL;
ALTER TABLE `STATISTICS` add `CENTROID_LON` double DEFAULT NULL;
