ALTER TABLE `STATISTICS` add `CREATION_TIME`     datetime DEFAULT NOW();
ALTER TABLE `STATISTICS` add `MODIFICATION_TIME` datetime DEFAULT NOW();

UPDATE `STATISTICS` set `CREATION_TIME` = NOW()     where `CREATION_TIME` IS NULL;
UPDATE `STATISTICS` set `MODIFICATION_TIME` = NOW() where `MODIFICATION_TIME` IS NULL;
