<link rel="stylesheet" href="/webjars/font-awesome/css/font-awesome.css" crossorigin="anonymous"/>

<link rel="stylesheet" href="/webjars/leaflet/dist/leaflet.css" crossorigin="anonymous"/>

<link rel="stylesheet" href="/webjars/leaflet.locatecontrol/dist/L.Control.Locate.css" crossorigin="anonymous"/>

<link rel="stylesheet" href="/webjars/leaflet.markercluster/dist/MarkerCluster.css" crossorigin="anonymous"/>

<link rel="stylesheet" href="/webjars/Leaflet.EditInOSM/Leaflet.EditInOSM.css" crossorigin="anonymous"/>
