<!DOCTYPE html>
<html>
<head>

    <title>OSM Mosques: Map</title>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="icon" type="image/x-icon" href="/favicons/fa-mosque-solid.ico"/>

    <link rel="stylesheet" href="/webjars/font-awesome/css/font-awesome.css" crossorigin="anonymous"/>

    <link rel="stylesheet" href="/webjars/leaflet/dist/leaflet.css" crossorigin="anonymous"/>

    <link rel="stylesheet" href="/webjars/leaflet.locatecontrol/dist/L.Control.Locate.css" crossorigin="anonymous"/>

    <link rel="stylesheet" href="/webjars/leaflet.markercluster/dist/MarkerCluster.css" crossorigin="anonymous"/>

    <link rel="stylesheet" href="/webjars/Leaflet.EditInOSM/Leaflet.EditInOSM.css" crossorigin="anonymous"/>

    <link rel="stylesheet" href="/css/navbar.css" crossorigin="anonymous"/>

    <link rel="stylesheet" href="/css/osm-mosques.css" crossorigin="anonymous"/>

</head>
<body>

<#include "navbar.ftlh">

<div id="map"></div>

<script src="/webjars/leaflet/dist/leaflet.js" crossorigin="anonymous"></script>

<script src="/webjars/leaflet.locatecontrol/dist/L.Control.Locate.min.js" crossorigin="anonymous"></script>

<script src="/webjars/leaflet.markercluster/dist/leaflet.markercluster-src.js" crossorigin="anonymous"></script>

<script src="/webjars/leaflet-providers/leaflet-providers.js" crossorigin="anonymous"></script>

<script src="/webjars/Leaflet.EditInOSM/Leaflet.EditInOSM.js" crossorigin="anonymous"></script>

<script src="/js/osm-mosques-map.js" crossorigin="anonymous"></script>

</body>
</html>
