<!DOCTYPE html>
<html>
<head>

    <title>OSM Mosques: Map</title>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="icon" type="image/x-icon" href="/favicons/fa-mosque-solid.ico"/>

    <link rel="stylesheet" href="/webjars/font-awesome/css/font-awesome.css" crossorigin="anonymous"/>

    <link rel="stylesheet" href="/webjars/leaflet/dist/leaflet.css" crossorigin="anonymous"/>

    <link rel="stylesheet" href="/css/osm-mosques.css" crossorigin="anonymous"/>

    <script src="/webjars/leaflet/dist/leaflet.js" crossorigin="anonymous"></script>

</head>
<body>

<div id="map"></div>

<script src="/js/osm-mosques-map.js" crossorigin="anonymous"></script>

</body>
</html>
